[package]
name = "showerserver"
version = "0.1.0"
edition = "2024"

[dependencies]
evdev = "0.13.2"

[profile.release]
opt-level = "z"     # Boyut optimizasyonu
lto = true          # Link-time optimization
codegen-units = 1   # Daha agresif kod optimizasyonu
panic = "abort"     # Unwind kodlarını ve allocation yükünü temizler